### ISSUE TITLE
Unable to deploy 

### ISSUE THREAD

**Issue by bharathpedem** [liprec/vsts-release-aas#102]
Hi Team, While we try to deploy the DB to AAS using this template we are getting the below error.
2022-05-11T13:18:55.8175112Z ##[section]Starting: Deploy DB to AAS
2022-05-11T13:18:55.8811419Z ==============================================================================
2022-05-11T13:18:55.8812059Z Task         : Tabular Database Deployment
2022-05-11T13:18:55.8812512Z Description  : Deploy tabular databases to Azure Analysis Services or Power BI Premium
2022-05-11T13:18:55.8812779Z Version      : 1.5.8
2022-05-11T13:18:55.8813080Z Author       : Jan Pieter Posthuma
2022-05-11T13:18:55.8813697Z Help         : [More Information](https://github.com/liprec/vsts-release-aas)
2022-05-11T13:18:55.8814399Z ==============================================================================
2022-05-11T13:18:57.9689609Z Added TLS 1.2 in session.
2022-05-11T13:18:58.3943266Z ##[warning]The 'overwrite' option will be deprecated in a future version.
2022-05-11T13:18:58.6950573Z ##[error]System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A socket operation was attempted to an unreachable network 169.254.169.254:80
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2022-05-11T13:18:58.7320754Z ##[section]Finishing: Deploy DB to AAS

**Comment by liprec** [comment]
Can you share the logging with parameter `System.Debug` set to `true`?
