### ISSUE TITLE
Add support for service connection authentication via certificates

### ISSUE THREAD

**Issue by yorickbouma** [liprec/vsts-release-aas#104]
Since last night we are receiving the following error when using the deployment task on a windows-2019 or windows-latest (2022) hosted agent.

Any ideas?

`2022-06-01T07:35:01.0420850Z ##[debug]Exception message - System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist.
2022-06-01T07:35:01.0430882Z ##[debug]   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
2022-06-01T07:35:01.0442264Z ##[debug]   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
2022-06-01T07:35:01.0453078Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
2022-06-01T07:35:01.0463998Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.0474721Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.0486838Z ##[debug]   at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[] value)
2022-06-01T07:35:01.0497814Z ##[debug]   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
2022-06-01T07:35:01.0507776Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.0518704Z ##[debug]   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
2022-06-01T07:35:01.0529036Z ##[debug]   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
2022-06-01T07:35:01.0539207Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.0549769Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2022-06-01T07:35:01.0560333Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-06-01T07:35:01.0571652Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.0582365Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.0592556Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-06-01T07:35:01.0603013Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-06-01T07:35:01.0613470Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2022-06-01T07:35:01.0623631Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2022-06-01T07:35:01.0633774Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2022-06-01T07:35:01.1634417Z ##[debug]Caught exception from task script.
2022-06-01T07:35:01.1663861Z ##[debug]Error record:
2022-06-01T07:35:01.2183823Z ##[debug]System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist.
2022-06-01T07:35:01.2193134Z ##[debug]   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
2022-06-01T07:35:01.2203868Z ##[debug]   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2214638Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2225884Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2237654Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2247758Z ##[debug]   at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[] value)
2022-06-01T07:35:01.2258762Z ##[debug]   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
2022-06-01T07:35:01.2268562Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.2279389Z ##[debug]   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
2022-06-01T07:35:01.2290132Z ##[debug]   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
2022-06-01T07:35:01.2301030Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.2311112Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2022-06-01T07:35:01.2321440Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2331634Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2341672Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2351722Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2361768Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-06-01T07:35:01.2372129Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2022-06-01T07:35:01.2382559Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2022-06-01T07:35:01.2393340Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2022-06-01T07:35:01.2404071Z ##[debug]At D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\VstsAzureRestHelperExtra_.psm1:217 char:9
2022-06-01T07:35:01.2413741Z ##[debug]+         throw $_.Exception.ToString()
2022-06-01T07:35:01.2424648Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-06-01T07:35:01.2435214Z ##[debug]    + CategoryInfo          : OperationStopped: (System.Manageme...Base.Complete():String) [], RuntimeException
2022-06-01T07:35:01.2447690Z ##[debug]    + FullyQualifiedErrorId : System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Path' to     the target. Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e82    6c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does     not exist." ---> System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find     path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Micros    oft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.ItemN    otFoundException: Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_module    s\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist.
2022-06-01T07:35:01.2456448Z ##[debug]       at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, P    SDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
2022-06-01T07:35:01.2467362Z ##[debug]       at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext co    ntext, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2477594Z ##[debug]       at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNon    existingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2487532Z ##[debug]       at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allow    NonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2498496Z ##[debug]       at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allow    NonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2508292Z ##[debug]   at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[] value)
2022-06-01T07:35:01.2519096Z ##[debug]       at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledComm    andParameter parameterMetadata)
2022-06-01T07:35:01.2528781Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.2539795Z ##[debug]       at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledComm    andParameter parameterMetadata)
2022-06-01T07:35:01.2549921Z ##[debug]       at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledC    ommandParameter parameterMetadata, ParameterBindingFlags flags)
2022-06-01T07:35:01.2559269Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.2570038Z ##[debug]       at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Excepti    on exception)
2022-06-01T07:35:01.2578715Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2588955Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2598966Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2608794Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2619845Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-06-01T07:35:01.2630211Z ##[debug]       at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputTo    Process)
2022-06-01T07:35:01.2640633Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2022-06-01T07:35:01.2650883Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2022-06-01T07:35:01.2661410Z ##[debug] 
2022-06-01T07:35:01.2677963Z ##[debug]Script stack trace:
2022-06-01T07:35:01.2710564Z ##[debug]at Get-AzureAnalysisServicesStatus, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\VstsAzureRestHelperExtra_.psm1: line 217
2022-06-01T07:35:01.2720992Z ##[debug]at <ScriptBlock>, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\deploy-aas-db.ps1: line 144
2022-06-01T07:35:01.2730909Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-06-01T07:35:01.2741251Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-06-01T07:35:01.2751368Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-06-01T07:35:01.2761669Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-06-01T07:35:01.2777366Z ##[debug]Exception:
2022-06-01T07:35:01.2819510Z ##[debug]System.Management.Automation.RuntimeException: System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist.
2022-06-01T07:35:01.2828220Z ##[debug]   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
2022-06-01T07:35:01.2838855Z ##[debug]   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2848613Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2858843Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2869018Z ##[debug]   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
2022-06-01T07:35:01.2879306Z ##[debug]   at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[] value)
2022-06-01T07:35:01.2889557Z ##[debug]   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
2022-06-01T07:35:01.2899449Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.2909429Z ##[debug]   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
2022-06-01T07:35:01.2920208Z ##[debug]   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
2022-06-01T07:35:01.2930161Z ##[debug]   --- End of inner exception stack trace ---
2022-06-01T07:35:01.2940412Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2022-06-01T07:35:01.2950354Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2960265Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2970892Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2981262Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-06-01T07:35:01.2991644Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-06-01T07:35:01.3001645Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2022-06-01T07:35:01.3012336Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2022-06-01T07:35:01.3022391Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2022-06-01T07:35:01.3091243Z ##[error]System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
   at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[] value)
   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
2022-06-01T07:35:01.3108571Z ##[debug]Processed: ##vso[task.logissue type=error]System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist." ---> System.Management.Automation.ItemNotFoundException: Cannot find path 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.5.8\ps_modules\VstsAzureRestHelpers_\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist.%0D%0A   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)%0D%0A   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)%0D%0A   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)%0D%0A   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)%0D%0A   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)%0D%0A   at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[%5D value)%0D%0A   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)%0D%0A   --- End of inner exception stack trace ---%0D%0A   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)%0D%0A   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)%0D%0A   --- End of inner exception stack trace ---%0D%0A   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)%0D%0A   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)%0D%0A   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)%0D%0A   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)%0D%0A   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)%0D%0A   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0%5D(T0 arg0)%0D%0A   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)%0D%0A   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()%0D%0A   at System.Management.Automation.CommandProcessorBase.Complete()
2022-06-01T07:35:01.3118770Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-06-01T07:35:01.3380369Z ##[section]Finishing: Deploy Demand and Supply Model`

**Comment by liprec** [comment]
Thanks for the feedback and I just ran a deployment in my environment with a `windows-latest` agent and it is running fine (of course).
Could you try again to see if it is a hickup in the agent?

**Comment by yorickbouma** [comment]
I think we found out why it happened. We recently switched from a secret on the service connection to a certificate on the service connection. My assumption is that the helpers/framework that you use to do the SPN part needs another dll in the case the SPN works with a certificate. For now we will switch back to a secret. However, maybe the .dll should be included to support this scenario? It is a bit outside my knowledge are so I'll leave it up to you for interpretation.

**Comment by yorickbouma** [comment]
You’re welcome. Let me know if/when you need help testing.

Let me use this moment to also thank you for this extension, your development and your support. It has been working perfectly for us. We will soon switch to Power BI Premium and are happy we can continue using your extension.
