### ISSUE TITLE
Issue with Task Script.

### ISSUE THREAD

**Issue by KyleJAnderson** [liprec/vsts-release-aas#2]
Hello, can you please investigate this? thank you for your time.

2017-08-23T17:50:31.7143905Z ##[debug]Caught exception from task script.
2017-08-23T17:50:31.7143905Z ##[debug]Error record:
2017-08-23T17:50:31.9019278Z ##[debug]D:\Agent\_work\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.0.0\deploy-aas-db.ps1 : Exception setting "members": "The property 'members' cannot be found on this object. Verify that the property exists and can be set."
2017-08-23T17:50:31.9019278Z ##[debug]At line:1 char:1
2017-08-23T17:50:31.9019278Z ##[debug]+ . 'D:\Agent\_work\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e8 ...
2017-08-23T17:50:31.9019278Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-08-23T17:50:31.9019278Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [deploy-aas-db.ps1], SetValueInvocationException
2017-08-23T17:50:31.9019278Z ##[debug]    + FullyQualifiedErrorId : ExceptionWhenSetting,deploy-aas-db.ps1
2017-08-23T17:50:31.9175469Z ##[debug] 
2017-08-23T17:50:31.9175469Z ##[debug]Script stack trace:
2017-08-23T17:50:31.9175469Z ##[debug]at RemoveSecurityIds, D:\Agent\_work\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.0.0\deploy-aas-db.psm1: line 99
2017-08-23T17:50:31.9331735Z ##[debug]at <ScriptBlock>, D:\Agent\_work\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.0.0\deploy-aas-db.ps1: line 58
2017-08-23T17:50:31.9331735Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-08-23T17:50:31.9331735Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-08-23T17:50:31.9331735Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-08-23T17:50:31.9331735Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-08-23T17:50:31.9487977Z ##[debug]Exception:
2017-08-23T17:50:31.9487977Z ##[debug]System.Management.Automation.SetValueInvocationException: Exception setting "members": "The property 'members' cannot be found on this object. Verify that the property exists and can be set." ---> System.Management.Automation.RuntimeException: The property 'members' cannot be found on this object. Verify that the property exists and can be set.
2017-08-23T17:50:31.9487977Z ##[debug]   at System.Management.Automation.Language.PSSetMemberBinder.SetAdaptedValue(Object obj, String member, Object value)
2017-08-23T17:50:31.9487977Z ##[debug]   --- End of inner exception stack trace ---
2017-08-23T17:50:31.9487977Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-08-23T17:50:31.9644178Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-08-23T17:50:31.9644178Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-08-23T17:50:31.9644178Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-08-23T17:50:31.9644178Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2017-08-23T17:50:31.9644178Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2017-08-23T17:50:31.9800602Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2017-08-23T17:50:31.9800602Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2017-08-23T17:50:31.9800602Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2017-08-23T17:50:32.0581540Z ##[error]Exception setting "members": "The property 'members' cannot be found on this object. Verify that the property exists and can be set."
2017-08-23T17:50:32.0581540Z ##[debug]Processed: ##vso[task.logissue type=error]Exception setting "members": "The property 'members' cannot be found on this object. Verify that the property exists and can be set."
2017-08-23T17:50:32.0581540Z ##[debug]Processed: ##vso[task.complete result=Failed]

**Comment by liprec** [comment]
Thanks for reporting this issue. This is caused because your model doesn't have any members in the roles which of course can be the case. 
I will fix this in the next couple of hours and push a new version to the marketplace.

**Comment by KyleJAnderson** [comment]
Thank you very much

**Comment by liprec** [comment]
Hi @KyleJAnderson,

I just published a new version of the extension and it should auto update.
Can you validate if it is fixed?

Thanks, JP

**Comment by KyleJAnderson** [comment]
Verified! You're a wizard! Thank you again

**Comment by alexmarshall132** [comment]
Thank you very much for your help Jan, it's much appreciated
