### ISSUE TITLE
openssl.exe missing error while executing the Deploy AAS DB task (v1.3.3)

### ISSUE THREAD

**Issue by jayanthpurushothaman** [liprec/vsts-release-aas#46]
While running the Azure Analysis Service Deployment task **Deploy Azure Analysis Service databases** on the Microsoft Hosted Agent, we are getting this error in the Azure Pipeline. It looks like openssl is missing in the bundle:

**Hosted Agent: (Region Central US)**

Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az363'
Current agent version: '2.173.0'
Operating System
Virtual Environment
Current image version: '20200802.1'
Agent running as: 'VssAdministrator'
##[debug]Triggering repository: as-ddm-marketing. repository type: Git
Prepare build directory.
##[debug]Creating build directory: 'D:\a\1'
##[debug]Delete existing artifacts directory: 'D:\a\1\a'
##[debug]Creating artifacts directory: 'D:\a\1\a'
##[debug]Delete existing test results directory: 'D:\a\1\TestResults'
##[debug]Creating test results directory: 'D:\a\1\TestResults'
##[debug]Creating binaries directory: 'D:\a\1\b'
##[debug]Creating source directory: 'D:\a\1\s'
Set build variables.
Download all required tasks.
Downloading task: deploy-aas-db (1.3.3)
##[debug]Task 'deploy-aas-db' has been downloaded into 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3'.
Checking job knob settings.
   Knob: AgentToolsDirectory = C:/hostedtoolcache/windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
##[debug]Log plugin 'TestResultLogPlugin' is disabled.
##[debug]Log plugin 'TestFilePublisherPlugin' is disabled.
Start tracking orphan processes.
Finishing: Initialize job

`
2020-08-06T17:56:44.1564081Z ##[debug]Evaluating condition for step: 'Deploy model to asazure://aspaaseastus2.asazure.windows.net/asddmegrrptdev'
2020-08-06T17:56:44.1566156Z ##[debug]Evaluating: SucceededNode()
2020-08-06T17:56:44.1566742Z ##[debug]Evaluating SucceededNode:
2020-08-06T17:56:44.1567827Z ##[debug]=> True
2020-08-06T17:56:44.1568451Z ##[debug]Result: True
2020-08-06T17:56:44.1569154Z ##[section]Starting: Deploy model to asazure://aspaaseastus2.asazure.windows.net/asddmegrrptdev
2020-08-06T17:56:44.1677571Z ==============================================================================
2020-08-06T17:56:44.1677976Z Task         : Azure Analysis Service Deployment
2020-08-06T17:56:44.1678296Z Description  : Deploy Azure Analysis Service databases
2020-08-06T17:56:44.1678573Z Version      : 1.3.3
2020-08-06T17:56:44.1678815Z Author       : Jan Pieter Posthuma
2020-08-06T17:56:44.1679178Z Help         : [More Information](https://github.com/liprec/vsts-deploy-aas)
2020-08-06T17:56:44.1679572Z ==============================================================================
.
.
.
.
.
2020-08-06T17:57:21.9684434Z ##[debug]Leaving Set-UserAgent_Core.
2020-08-06T17:57:21.9709491Z ##[command]Clear-AzureRmContext -Scope Process
2020-08-06T17:57:22.9664781Z ##[command]Disable-AzureRmContextAutosave -ErrorAction Stop
2020-08-06T17:57:23.7112975Z ##[debug]Entering Invoke-VstsTool.
2020-08-06T17:57:23.7130383Z ##[debug] FileName: 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\openssl\openssl.exe'
2020-08-06T17:57:23.7146811Z ##[debug] Arguments: 'pkcs12 -export -in D:\a\_temp\clientcertificate.pem -out D:\a\_temp\clientcertificate.pfx -password file:"D:\a\_temp\clientcertificatepassword.txt"'
2020-08-06T17:57:23.7162192Z ##[debug] RequireExitCodeZero: 'True'
2020-08-06T17:57:23.7187261Z ##[command]"D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\openssl\openssl.exe" pkcs12 -export -in D:\a\_temp\clientcertificate.pem -out D:\a\_temp\clientcertificate.pfx -password file:"D:\a\_temp\clientcertificatepassword.txt"
2020-08-06T17:57:23.8623068Z ##[debug]Leaving Invoke-VstsTool.
2020-08-06T17:57:23.8687580Z ##[debug]Leaving Initialize-Azure.
2020-08-06T17:57:23.8742741Z ##[debug]Caught exception from task script.
2020-08-06T17:57:23.8771671Z ##[debug]Error record:
2020-08-06T17:57:23.9483920Z ##[debug]Invoke-Expression : The term 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\openssl\openssl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-08-06T17:57:23.9494688Z ##[debug]At D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsTaskSdk\ToolFunctions.ps1:107 char:9
2020-08-06T17:57:23.9506522Z ##[debug]+         Invoke-Expression "& '$FileName' --% $Arguments"
2020-08-06T17:57:23.9517562Z ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-08-06T17:57:23.9528681Z ##[debug]    + CategoryInfo          : ObjectNotFound: (D:\a\_tasks\dep...ssl\openssl.exe:String) [Invoke-Expression], CommandN    otFoundException
2020-08-06T17:57:23.9539411Z ##[debug]    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
2020-08-06T17:57:23.9550413Z ##[debug] 
2020-08-06T17:57:23.9567973Z ##[debug]Script stack trace:
2020-08-06T17:57:23.9601399Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-08-06T17:57:23.9613574Z ##[debug]at Invoke-Tool, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsTaskSdk\ToolFunctions.ps1: line 107
2020-08-06T17:57:23.9624302Z ##[debug]at ConvertTo-Pfx, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\Utility.ps1: line 230
2020-08-06T17:57:23.9635375Z ##[debug]at Add-Certificate, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\Utility.ps1: line 13
2020-08-06T17:57:23.9646711Z ##[debug]at Initialize-AzureSubscription, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 160
2020-08-06T17:57:23.9657185Z ##[debug]at Initialize-Azure, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\VstsAzureHelpers_.psm1: line 58
2020-08-06T17:57:23.9669069Z ##[debug]at <ScriptBlock>, D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\deploy-aas-db.ps1: line 40
2020-08-06T17:57:23.9679667Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-08-06T17:57:23.9691075Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-08-06T17:57:23.9701882Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-08-06T17:57:23.9714181Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-08-06T17:57:23.9730954Z ##[debug]Exception:
2020-08-06T17:57:23.9777697Z ##[debug]System.Management.Automation.CommandNotFoundException: The term 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\openssl\openssl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-08-06T17:57:23.9788505Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2020-08-06T17:57:23.9799338Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction
2.Run(InterpretedFrame frame)
2020-08-06T17:57:23.9810541Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-08-06T17:57:23.9821265Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-08-06T17:57:23.9832754Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2020-08-06T17:57:23.9843482Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2020-08-06T17:57:23.9854632Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2020-08-06T17:57:23.9865467Z ##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
2020-08-06T17:57:23.9876304Z ##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
2020-08-06T17:57:23.9887338Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
2020-08-06T17:57:23.9897971Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
2020-08-06T17:57:23.9908856Z ##[debug]   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
2020-08-06T17:57:23.9919578Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2020-08-06T17:57:23.9977061Z ##[error]The term 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\openssl\openssl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-08-06T17:57:23.9979623Z ##[debug]Processed: ##vso[task.logissue type=error]The term 'D:\a\_tasks\deploy-aas-db_a55f5b79-9828-4b7f-9528-85e9e826c028\1.3.3\ps_modules\VstsAzureHelpers_\openssl\openssl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020-08-06T17:57:23.9992573Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-08-06T17:57:24.0740253Z ##[section]Finishing: Deploy model to asazure://aspaaseastus2.asazure.windows.net/asddmegrrptdev
`

**Comment by liprec** [comment]
Hi @jayanthpurushothaman,

Just to confirm my analysis: you are using a certificate with a service principal to connect to Azure?
If so, it looks like the task does not support this as openssl is not included with the extension.

-JP

**Comment by jayanthpurushothaman** [comment]
@liprec Yes that's correct, our SPN uses Certificate method authentication to Azure. Is there a workaround to this issue, if we have to make it work with SPN with Cert auth?

**Comment by jayanthpurushothaman** [comment]
@liprec This works perfectly with SPN + Client Secret. Thanks. I will close this issue.
